In [1]:

%matplotlib inline

from sqlalchemy import create_engine
import datetime
import numpy as np
import pandas as pd
import urllib2
import json


import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as col
from matplotlib.dates import  DateFormatter
import seaborn as sns
from pandas.io.json import json_normalize

from config import *
import holidays_service
import db_service

In [2]:
holidays_service.get_holidays()

Index([u'2520', u'1425', u'1069', u'2643', u'2770', u'1541', u'2978', u'2829'], dtype='object')
Finished to retrieve holidays.

In [147]:
dateparse = lambda x: pd.datetime.strptime(x, '%d.%m.%Y')

In [148]:
df_public = pd.read_csv('holidays/public_holidays.csv',index_col=0,parse_dates=['ft_date'],sep=';', date_parser=dateparse)
df_school = pd.read_csv('holidays/school_holidays.csv',index_col=0,parse_dates=['date_begin','date_end'],sep=';', date_parser=dateparse)
df_public.head()

   ft_class    ft_date  ft_id        ft_name  holidays_API_site_id
0         2 2017-01-01      1    Neujahrstag                  2520
1         1 2017-01-02      3  Berchtoldstag                  2520
2         2 2017-04-14     17     Karfreitag                  2520
3         4 2017-04-16     18         Ostern                  2520
4         2 2017-04-17     19    Ostermontag                  2520

In [149]:
df_school.sort_values(by='date_begin').head(3)

,date_begin,date_end,note,percent,prov,sc_id,sc_name,holidays_API_site_id
0,2016-12-23,2017-01-08,NaN,100,0,397547,Winterferien,2520
0,2016-12-23,2017-01-08,NaN,100,0,400568,Winterferien,2643
0,2016-12-24,2017-01-08,NaN,100,0,435754,Weihnachtsferien,2829

In [150]:
df_school.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 75 entries, 0 to 9
Data columns (total 8 columns):
date_begin              75 non-null datetime64[ns]
date_end                75 non-null datetime64[ns]
note                    0 non-null float64
percent                 75 non-null int64
prov                    75 non-null int64
sc_id                   75 non-null int64
sc_name                 75 non-null object
holidays_API_site_id    75 non-null int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(1)
memory usage: 5.3+ KB

In [151]:
date_range=pd.date_range(datetime.date(2014,1,1),datetime.date(2017,1,10))

In [152]:
df_school[df_school.holidays_API_site_id==2978]

,date_begin,date_end,note,percent,prov,sc_id,sc_name,holidays_API_site_id
0,2016-12-26,2017-01-06,NaN,100,0,452266,Weihnachtsferien,2978
1,2017-02-20,2017-03-03,NaN,100,0,452267,Sportferien,2978
2,2017-04-13,2017-04-17,NaN,100,0,452268,Osterferien,2978
3,2017-04-24,2017-05-05,NaN,100,0,452269,Fr√ºhlingsferien,2978
4,2017-05-25,2017-05-28,NaN,100,0,452270,Auffahrtsferien,2978
5,2017-06-05,2017-06-05,NaN,100,0,452271,Pfingstmontag,2978
6,2017-07-17,2017-08-18,NaN,100,0,452272,Sommerferien,2978
7,2017-10-09,2017-10-20,NaN,100,0,452273,Herbstferien,2978
8,2017-12-25,2018-01-05,NaN,100,0,452274,Weihnachtsferien,2978

In [153]:
df_school_reindexed = df_school.set_index(['holidays_API_site_id','date_begin'])
df_school_reindexed = df_school_reindexed.groupby(level='holidays_API_site_id').apply(
      lambda x: x.reset_index().set_index('date_begin').sort_index().reindex(date_range,method='ffill'))
df_school_reindexed = df_school_reindexed.drop('holidays_API_site_id',1)

In [159]:

df_school_reindexed= df_school_reindexed.fillna(0)
df_school_reindexed = df_school_reindexed.reset_index(level=1, drop=False)
df_school_reindexed.tail(10)

,holidays_API_site_id,level_1,date_end,note,percent,prov,sc_id,sc_name,is_holiday
8838,2978,2017-01-01,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8839,2978,2017-01-02,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8840,2978,2017-01-03,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8841,2978,2017-01-04,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8842,2978,2017-01-05,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8843,2978,2017-01-06,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
8844,2978,2017-01-07,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
8845,2978,2017-01-08,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
8846,2978,2017-01-09,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
8847,2978,2017-01-10,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True

In [158]:
df_school_reindexed['is_holiday'] = (df_school_reindexed.date_end<df_school_reindexed.level_1) 
& (df_school_reindexed.date_end!=)
df_school_reindexed.tail(20)

,level_1,date_end,note,percent,prov,sc_id,sc_name,is_holiday
holidays_API_site_id,,,,,,,,
2978,2016-12-22,1970-01-01,0.0,0.0,0.0,0.0,0,True
2978,2016-12-23,1970-01-01,0.0,0.0,0.0,0.0,0,True
2978,2016-12-24,1970-01-01,0.0,0.0,0.0,0.0,0,True
2978,2016-12-25,1970-01-01,0.0,0.0,0.0,0.0,0,True
2978,2016-12-26,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2016-12-27,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2016-12-28,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2016-12-29,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2016-12-30,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2016-12-31,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-01,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-02,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-03,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-04,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-05,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-06,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,False
2978,2017-01-07,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
2978,2017-01-08,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
2978,2017-01-09,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True
2978,2017-01-10,2017-01-06,0.0,100.0,0.0,452266.0,Weihnachtsferien,True